env:
  browser: true
  es2021: true
extends:
  - eslint-config-prettier
  - eslint:recommended
  - standard-with-typescript
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/recommended
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended
parser: vue-eslint-parser
parserOptions:
  ecmaVersion: latest
  sourceType: module
  parser: "@typescript-eslint/parser"
plugins:
  - vue
globals:
  defineProps: readonly
  defineEmits: readonly
  defineExpose: readonly
  withDefaults: readonly
rules: {
}
