/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACollapse: typeof import('ant-design-vue/es')['Collapse']
    ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AForm: (typeof import("ant-design-vue/es"))["Form"]
    AFormItem: (typeof import("ant-design-vue/es"))["FormItem"]
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: (typeof import("ant-design-vue/es"))["Menu"]
    AMenuItem: (typeof import("ant-design-vue/es"))["MenuItem"]
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATree: typeof import('ant-design-vue/es')['Tree']
    FaqView: typeof import('./src/components/help/FaqView.vue')['default']
    Footerview: typeof import('./src/components/Footerview.vue')['default']
    FooterView: typeof import('./src/components/FooterView.vue')['default']
    ForumTree: typeof import('./src/components/forum/ForumTree.vue')['default']
    HomeView: typeof import('./src/components/home/HomeView.vue')['default']
    InfoCompletionModal: typeof import('./src/components/user/InfoCompletionModal.vue')['default']
    LoginFaq: typeof import('./src/components/help/LoginFaq.vue')['default']
    LoginView: typeof import('./src/components/login/LoginView.vue')['default']
    NotificationBox: typeof import('./src/components/home/NotificationBox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
