/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    AddComment: typeof import('./src/components/forum/post/comment/AddComment.vue')['default']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASpace: (typeof import("ant-design-vue/es"))["Space"]
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATree: typeof import('ant-design-vue/es')['Tree']
    AUpload: typeof import('ant-design-vue/es')['Upload']
    CommentComponent: (typeof import("./src/components/forum/post/editor/CommentComponent.vue"))["default"]
    copy: (typeof import("./src/components/user/UserSmallProfileContent.vue"))["default"]
    EditorComponent: typeof import('./src/components/forum/post/editor/EditorComponent.vue')['default']
    ForumTree: typeof import('./src/components/forum/ForumTree.vue')['default']
    ImageCropper: typeof import('./src/components/helper/ImageCropper.vue')['default']
    InfoCompletionModal: typeof import('./src/components/user/InfoCompletionModal.vue')['default']
    NotificationBox: typeof import('./src/components/home/NotificationBox.vue')['default']
    PostToolbar: typeof import('./src/components/forum/post/PostToolbar.vue')['default']
    ReplyComponent: typeof import('./src/components/forum/post/ReplyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBarUserCard: typeof import('./src/components/user/StatusBarUserCard.vue')['default']
    TinyMceEditor: typeof import('./src/components/forum/editor/TinyMceEditor.vue')['default']
    UserProfileCard: typeof import('./src/components/user/UserProfileCard.vue')['default']
    UserSmallProfile: typeof import('./src/components/user/UserSmallProfile.vue')['default']
    UserSmallProfileContent: typeof import('./src/components/user/UserSmallProfileContent.vue')['default']
  }
}
